# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAMAnimatedTabBarController' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

end

target 'RAMAnimatedTabBarDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RAMAnimatedTabBarDemo
  pod 'FSCalendar'
  pod 'Floaty'
  pod 'JJFloatingActionButton'
  pod 'EAIntroView'
  pod 'SMPageControl'
  pod 'Firebase/Analytics'


end
